# Site settings
title: Vishal Polley Blog 
description: I love grasping new concepts related to computer world and intend to apply them into real world for the welfare of the society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vishalpolley.github.io" # the base hostname & protocol for your site e.g. https://vishalpolley.github.io

# User settings
username: Vishal Polley
user_description: I love grasping new concepts related to computer world and intend to apply them into real world for the welfare of the society.
user_title: "Computer Vision, Open Source and Python Enthusiast :snake:"
email: vishalpolley290996@gmail.com
twitter_username: vishalpolley
github_username:  vishalpolley
gplus_username:  115857569839787281749
disqus_username: vishalpolley

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
